<?php
/**
 * Created by PhpStorm.
 * User: 游贤川
 * Date: 2018/1/4
 * Time: 19:55
 */

namespace backend\filters;


use yii\base\ActionFilter;

class CheckFilter extends ActionFilter
{



   public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}